# Generated by Django 5.2.6 on 2025-12-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('total_stock', models.IntegerField(default=0, null=True)),
                ('add_stock', models.PositiveIntegerField(default=0, null=True)),
                ('reduce_stock', models.PositiveIntegerField(default=0, null=True)),
                ('shortage_threshold', models.IntegerField(default=1)),
                ('closest_expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('expiring_soon_alert_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('sales_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('items', models.JSONField()),
                ('total_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keep_inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keep_inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
