# Generated by Django 5.2.6 on 2025-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='items',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='product_name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
