# Generated by Django 5.2.6 on 2025-10-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='SalesDetails',
            new_name='SalesDetail',
        ),
    ]
