# Generated by Django 5.2.6 on 2025-12-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetail',
            name='sales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesdetail', to='keep_inventory.sale'),
        ),
    ]
