# Generated by Django 5.2.6 on 2025-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closest_expiry_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shortage_threshold',
            field=models.IntegerField(default=1),
        ),
    ]
