# Generated by Django 5.2.6 on 2025-12-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0002_alter_salesdetail_sales_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='product_id',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='sales_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesdetail', to='keep_inventory.sale'),
        ),
    ]
