# Generated by Django 5.2.6 on 2025-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0002_rename_total_amount_salesdetail_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='total_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
