# Generated by Django 5.2.6 on 2025-10-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0002_rename_sales_sale_rename_salesdetails_salesdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
