# Generated by Django 5.2.6 on 2026-02-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0003_rename_product_id_stockadjustment_sku_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
