# Generated by Django 5.2.6 on 2025-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0003_product_unit_price_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
