# Generated by Django 5.2.6 on 2025-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0003_rename_amount_salesdetail_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetail',
            name='items',
            field=models.JSONField(),
        ),
    ]
