# Generated by Django 5.2.6 on 2026-02-25 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0004_delete_stockadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('rate', models.IntegerField()),
                ('reason', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keep_inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
