# Generated by Django 5.2.6 on 2025-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0004_product_quantity_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='unit_cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
