# Generated by Django 5.2.6 on 2025-11-01 23:02

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0005_rename_unit_price_product_unit_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_profit',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('unit_selling_price'), '-', models.F('unit_cost_price')), output_field=models.DecimalField(decimal_places=2, max_digits=10)),
        ),
    ]
