# Generated by Django 5.2.6 on 2026-03-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0005_stockadjustment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
