# Generated by Django 5.2.6 on 2025-11-02 00:14

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0006_product_unit_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_profit',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('unit_profit'), '*', models.F('quantity_in_stock')), output_field=models.DecimalField(decimal_places=2, max_digits=10)),
        ),
    ]
