# Generated by Django 5.2.6 on 2026-03-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0006_delete_stockadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AddStock',
            fields=[
                ('addStockID', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, null=True)),
                ('shortage_threshold', models.IntegerField(default=1)),
                ('closest_expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('expiring_soon_alert_date', models.DateField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keep_inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RemoveStock',
            fields=[
                ('removeStockID', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField(default=0, null=True)),
                ('reason', models.CharField(choices=[('Unwholesome', 'Unwholesome'), ('Expired', 'Expired'), ('Other', 'Other')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keep_inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
