# Generated by Django 5.2.6 on 2025-11-03 23:03

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0007_product_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('add_stock'), '+', models.F('quantity_in_stock')), output_field=models.IntegerField(null=True)),
        ),
    ]
