# Generated by Django 5.2.6 on 2025-11-05 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0008_product_add_stock_alter_product_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_id',
            field=models.BigIntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='sales_detail_id',
            field=models.BigIntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
