# Generated by Django 5.2.6 on 2026-03-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0008_remove_removestock_sku_remove_removestock_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='stockInID',
            new_name='stock_in_ID',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='stockOutID',
            new_name='stock_out_ID',
        ),
    ]
