# Generated by Django 5.2.6 on 2025-11-07 14:54

import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_inventory', '0009_remove_product_id_remove_sale_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_profit',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('unit_profit'), '*', models.F('quantity_in_stock')), output_field=models.DecimalField(decimal_places=2, max_digits=10, null=True)),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_profit',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('unit_selling_price'), '-', models.F('unit_cost_price')), output_field=models.DecimalField(decimal_places=2, max_digits=10, null=True)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='sales_detail_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
